# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "knife-ec2"
  s.version = "0.5.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["adam@opscode.com", "schisamo@opscode.com"]
  s.date = "2011-10-24"
  s.description = "This is the official Opscode Knife plugin for EC2. This plugin gives knife the ability to create, bootstrap, and manage EC2 instances."
  s.email = ["Adam Jacob", "Seth Chisamore"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "knife-ec2.gemspec",
    "lib/chef/knife/ec2_base.rb",
    "lib/chef/knife/ec2_instance_data.rb",
    "lib/chef/knife/ec2_server_create.rb",
    "lib/chef/knife/ec2_server_delete.rb",
    "lib/chef/knife/ec2_server_list.rb",
    "lib/knife-ec2/version.rb",
    "spec/spec_helper.rb",
    "spec/unit/ec2_server_create_spec.rb"
  ]
  s.homepage = "http://wiki.opscode.com/display/chef"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Amazon EC2 Support for Chef's Knife Command"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chef>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0.8.2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<chef>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0.8.2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<chef>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0.8.2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

